### ISSUE TITLE
CIFAR100 Code

### ISSUE THREAD

**Issue by Itsnotbigdeal** [hunto/DiffKD#10]
Hello, I am very interested in your research and would like to conduct further experiments based on it. Can you provide the configuration file of Diffkd on CIFAR100.

**Comment by tara0907** [comment]
> 您好，我对您的研究很感兴趣，想在此基础上进行进一步的实验。请问您能提供一下 Diffkd 在 CIFAR100 上的配置文件吗？

=我也遇到了这个问题，请问您解决了没有？
