### ISSUE TITLE
diffkd_modules.py

### ISSUE THREAD

**Issue by nameLiMing** [hunto/DiffKD#2]
image = self.scheduler.add_noise_diff2(feat, noise, timesteps)
我从https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/ddim/pipeline_ddim.py
代码中没有找到这个方法。
然后使用其中的add_noise()方法也会出错。
请问这个方法是自己写的吗？

**Comment by hunto** [comment]
是的，diff2可以见
https://github.com/hunto/DiffKD/blob/5367f445c2a9fcedd3ac75e99a925bcdd7e8a5fa/scheduling_ddim.py#L356

我这里代码是可以正常跑的，你可能import错了一个scheduling_ddim.py。

**Comment by nameLiMing** [comment]
好的，谢谢，确实是我import错了

**Comment by Itsnotbigdeal** [comment]
@nameLiMing 想问下你有复现过CIFAR100上的实验吗，能达到论文里的效果吗
