### ISSUE TITLE
Is there a log file about the output of noise adapter???

### ISSUE THREAD

**Issue by omglet1** [hunto/DiffKD#3]
I am very interested in the noise adapter, because the module can measure the noisy level of each student feature adaptively and specifies a corresponding Gaussian noise to the feature to match the correct noisy level in initialization.
I would like to know more about the learning process of this module. 
Can you provide a log file of the output of the adaptive noise matching module during training? Thank you.

**Comment by hunto** [comment]
Hi @omglet1 ,

Thank you for your interest on our paper. Sorry we do not have a log file that shows the noisy levels during the training. But we have measured some stastistical data during the training, see the figure below.

![image](https://github.com/hunto/DiffKD/assets/23501718/fbe6c683-4588-49e4-8dcd-1263918d25f0)

The γ controls how much additional noise should be added to the student feature (larger γ, larger additional noise). It is interesting to see that, the γ becomes smaller along with the training procedure. I think a reason to this is that the student gets better during the training, and its feature is thus being less noisier.

**Comment by Itsnotbigdeal** [comment]
@omglet1 May I ask if you have replicated the experiment on CIFAR100 and achieved the effect described in the paper
